### ISSUE TITLE
Unable to start .exe (Not found vcruntime140D.dll, msvcp140d.dll, ucrtbased.dll)

### ISSUE THREAD

**Issue by UltrawideLover** [meik1710/IW4xUltraWide#1]
Hello, I downloaded the external .exe (folder: debug) but I am not able to start the fix. I installed/reinstalled every vcredist I could found. 

Thank you very much! Greetings! 

System: Windows 10
(Errors: Not found vcruntime140D.dll, msvcp140d.dll, ucrtbased.dll)

**Comment by UltrawideLover** [comment]
Ok, I fixed it: You need to install Visual Studio 2017 to run the .exe! Works flawless! Thank you very very much!

**Comment by meik1710** [comment]
Yes, thats a Visual C++ Redistributable issue. 
Great that you fixed it! have fun
